theme: minima
title: "Injainers 3 - Lore"
author: "John Stiven"
email: "your-email@example.com"
description: "Blog sobre el lore del servidor Injainers 3, sus participantes y aventuras."
baseurl: "" # Change if using a subdirectory (e.g., "/blog")
url: "https://yourdomain.com" # Change this to your actual site URL
